baseURL: https://tomsachsarchive.org/
languageCode: en-us
title: Tom Sachs Archive
theme: tsa
enableRobotsTXT: true

outputs:
  home: ["json", "HTML", "RSS"]
  section: ["json", "HTML"]


outputFormats:
  RSS:
    mediatype: "application/rss"
    baseName: "rss"

markup:
  goldmark:
    renderer:
      unsafe: true